version: 2.1
jobs:
  build:
    machine:
      image: ubuntu-2204:current
    working_directory: ~/go/src/github.com/fnproject/fn
    environment: # apparently expansion doesn't work here yet: https://discuss.circleci.com/t/environment-variable-expansion-in-working-directory/11322
      - GO111MODULE=on
      - GOPATH=/home/circleci/go
      - GOFLAGS=-mod=vendor
      - GOVERSION=1.13.15
      - # OS/ARCH are for the go tooling that running on circle CI server. Not for building Fn Server
      - OS=linux
      - ARCH=amd64
      - FN_LOG_LEVEL=debug
      - BUILDX_PLATFORMS: linux/amd64,linux/arm64
      - DIND_VERSION=24.0.9-dind
    steps:
      - checkout
      # install Go
      - run: |
          go version
          go env GOROOT
          mkdir tmp
          cd tmp
          sudo rm -rf /usr/local/go
          wget https://go.dev/dl/go$GOVERSION.$OS-$ARCH.tar.gz
          sudo tar -C /usr/local -xzf go$GOVERSION.$OS-$ARCH.tar.gz
      - run: go version
      # install latest Docker
      - run: |
          sudo rm -rf /var/cache/apt/archives && sudo ln -s ~/.apt-cache /var/cache/apt/archives && mkdir -p ~/.apt-cache/partial
          sudo service docker stop
          curl -fsSL https://get.docker.com/ | sudo sh
          docker version
      - run: docker version
      - run: nproc
      # fixes git-diff warning: "warning: inexact rename detection was skipped due to too many files.""
      - run: git config diff.renamelimit 65535
      # NOTE: if GOFLAGS and GOMODULE are set, gosec will be noisy. unset them (run this before any 'make' command)
      - run: |
          GOPATH=/home/circleci/go:$GOPATH
          wget -O - -q https://raw.githubusercontent.com/securego/gosec/master/install.sh | sh -s -- -b $GOPATH/bin 1.2.0
          $GOPATH/bin/gosec -quiet -severity medium ./...

      - run: make clear-images

      # Work out what needs rebuilding and what has changed
      - run: |
          ( ./changed-since-last.sh
            echo "export DIND_NEEDED DIND_TAG DIND_PREV"
            echo "export FN_NEEDED FN_TAG FN_PREV"
          ) >> $BASH_ENV

      # Rebuild the build tools if necessary

      # Install buildx for multi arch build in Circle CI
      - run:
          name: Install buildx
          command: |
            BUILDX_BINARY_URL="https://github.com/docker/buildx/releases/download/v0.30.1/buildx-v0.30.1.linux-amd64"

            curl --output docker-buildx \
              --silent --show-error --location --fail --retry 3 \
              "$BUILDX_BINARY_URL"

            mkdir -p ~/.docker/cli-plugins

            mv docker-buildx ~/.docker/cli-plugins/
            chmod a+x ~/.docker/cli-plugins/docker-buildx

            docker buildx install
            # Run binfmt
            docker run --rm --privileged tonistiigi/binfmt:latest --install "$BUILDX_PLATFORMS"

      # Rebuild system test image if necessary
      # Single arch image build is enough for running system test
      - run: |
          if [[ -n "$FN_NEEDED" ]]; then
            export DOCKER_BUILDKIT=0
            make test -j $(nproc)
          fi

      - deploy:
          command: |
            # TODO: rollback test change here
            if [[ "${CIRCLE_BRANCH}" == "marleung/multi-arch-build" && -z "${CIRCLE_PR_REPONAME}" ]]; then
              printenv DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
              git config --global user.email "ci@fnproject.com"
              git config --global user.name "CI"
              git branch --set-upstream-to=origin/${CIRCLE_BRANCH} ${CIRCLE_BRANCH}

              if [[ -n "$FN_NEEDED" ]]; then
                make release-fnserver
              fi
            fi
