version: 2.1
jobs:
  build:
    machine:
      image: ubuntu-2204:current
    working_directory: ~/go/src/github.com/fnproject/fn
#    environment: # apparently expansion doesn't work here yet: https://discuss.circleci.com/t/environment-variable-expansion-in-working-directory/11322
#      - GO111MODULE=on
#      - GOPATH=/home/circleci/go
#      - GOFLAGS=-mod=vendor
#      - GOVERSION=1.24.11
#      - # OS/ARCH are for the go tooling that running on circle CI server. Not for building Fn Server
#      - OS=linux
#      - ARCH=amd64
#      - FN_LOG_LEVEL=debug
#      - BUILDX_PLATFORMS: linux/amd64,linux/arm64
    steps:
      - skip ci for external PR
        - run: |
          echo "Skip CI for now for external PR. CI has been moved to oracle internal pipeline."
          echo "Please leave comment in the repo if you want to request to resurrect the Circle CI pipeline."
#      - checkout
#        # install Go
#      - run: |
#          go version
#          go env GOROOT
#          mkdir tmp
#          cd tmp
#          sudo rm -rf /usr/local/go
#          wget https://go.dev/dl/go$GOVERSION.$OS-$ARCH.tar.gz
#          sudo tar -C /usr/local -xzf go$GOVERSION.$OS-$ARCH.tar.gz
#      - run: go version
#      # install latest Docker
#      - run: |
#          sudo rm -rf /var/cache/apt/archives && sudo ln -s ~/.apt-cache /var/cache/apt/archives && mkdir -p ~/.apt-cache/partial
#          sudo service docker stop
#          curl -fsSL https://get.docker.com/ | sudo sh
#          docker version
#      - run: docker version
#      - run: nproc
#      # fixes git-diff warning: "warning: inexact rename detection was skipped due to too many files.""
#      - run: git config diff.renamelimit 65535
#      # NOTE: if GOFLAGS and GOMODULE are set, gosec will be noisy. unset them (run this before any 'make' command)
#      - run: |
#          GOPATH=/home/circleci/go:$GOPATH
#          wget -O - -q https://raw.githubusercontent.com/securego/gosec/master/install.sh | sh -s -- -b $GOPATH/bin 1.2.0
#          $GOPATH/bin/gosec -quiet -severity medium ./...
#
#      - run: make clear-images
#
#      # Work out what needs rebuilding and what has changed
#      - run: |
#          ( ./changed-since-last.sh
#            echo "export DIND_NEEDED DIND_TAG DIND_PREV"
#            echo "export FN_NEEDED FN_TAG FN_PREV"
#          ) >> $BASH_ENV
#
#      # Rebuild system test image if necessary
#      # Single arch image build is enough for running system test
#      - run: |
#          if [[ -n "$FN_NEEDED" ]]; then
#            make test -j $(nproc)
#          fi
#