package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
)

/*GroupWrapper group wrapper

swagger:model GroupWrapper
*/
type GroupWrapper struct {

	/* group

	Required: true
	*/
	Group *Group `json:"group"`
}

// Validate validates this group wrapper
func (m *GroupWrapper) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateGroup(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *GroupWrapper) validateGroup(formats strfmt.Registry) error {

	if m.Group != nil {

		if err := m.Group.Validate(formats); err != nil {
			return err
		}
	}

	return nil
}
