package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/validate"
)

/*NewTasksWrapper new tasks wrapper

swagger:model NewTasksWrapper
*/
type NewTasksWrapper struct {

	/* tasks

	Required: true
	*/
	Tasks []*NewTask `json:"tasks"`
}

// Validate validates this new tasks wrapper
func (m *NewTasksWrapper) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateTasks(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *NewTasksWrapper) validateTasks(formats strfmt.Registry) error {

	if err := validate.Required("tasks", "body", m.Tasks); err != nil {
		return err
	}

	return nil
}
