package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/validate"
)

/*TasksWrapper tasks wrapper

swagger:model TasksWrapper
*/
type TasksWrapper struct {

	/* Used to paginate results. If this is returned, pass it into the same query again to get more results.
	 */
	Cursor string `json:"cursor,omitempty"`

	/* error
	 */
	Error *ErrorBody `json:"error,omitempty"`

	/* tasks

	Required: true
	*/
	Tasks []*Task `json:"tasks"`
}

// Validate validates this tasks wrapper
func (m *TasksWrapper) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateTasks(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *TasksWrapper) validateTasks(formats strfmt.Registry) error {

	if err := validate.Required("tasks", "body", m.Tasks); err != nil {
		return err
	}

	return nil
}
