package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
)

/*TaskWrapper task wrapper

swagger:model TaskWrapper
*/
type TaskWrapper struct {

	/* task

	Required: true
	*/
	Task *Task `json:"task"`
}

// Validate validates this task wrapper
func (m *TaskWrapper) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateTask(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *TaskWrapper) validateTask(formats strfmt.Registry) error {

	if m.Task != nil {

		if err := m.Task.Validate(formats); err != nil {
			return err
		}
	}

	return nil
}
